
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME_BD']%>
  password: <%= ENV['PASSWORD_BD'] %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>

development:
  <<: *default
  database: new_api_development

test:
  <<: *default
  database: new_api_test

production:
  <<: *default
  database: new_api_production

